USE ARTISTA;
GO

SELECT * FROM EMPRESA
SELECT * FROM ARTISTAS
SELECT * FROM LANCAMENTO
SELECT * FROM ALBUM
SELECT * FROM ESTILO

SELECT titulo,nomeArtista ,nomeEstilo FROM ALBUM
LEFT JOIN ARTISTAS
ON ALBUM.idArtistas = ARTISTAS.idArtistas
LEFT JOIN ALBUM_ESTILO
ON ALBUM.idAlbum = ALBUM_ESTILO.idAlbum
LEFT JOIN ESTILO
ON ALBUM_ESTILO.idEstilo = ESTILO.idEstilo
GO