USE ARTISTA;
GO

INSERT INTO USUARIO(nomeUser,nomeEmail,senha)
VALUES ('ENZZO','ENZZO@EMAIL.COM','1ENZZO1'),('MA','MA@EMAIL.COM','123MA123');
GO

INSERT INTO EMPRESA(nomeEmpresa)
VALUES ('SO MUSICA TOP');
GO

INSERT INTO ARTISTAS(idEmpresa,nomeArtista)
VALUES (1,'MATUE'), (1,'OS BAROES DA P');
GO

INSERT INTO LANCAMENTO(idArtistas,dataLancamento)
VALUES (5,'06/09'), (4,'07/11');
GO

INSERT INTO ALBUM (idLancamento, nomeAlbum)
VALUES (1,'TA ROCHEDA'), (2,'MAQUINA DO TEMP');
GO

DELETE FROM ALBUM
WHERE idAlbum IN(5,6);

INSERT INTO ESTILO(idAlbum, Genero)
VALUES (4,'TRAP'), (3,'FORRO');
GO