CREATE DATABASE ARTISTA;
GO

USE ARTISTA;
GO

CREATE TABLE USUARIO (
	idUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeUser VARCHAR(15) NOT NULL,
	nomeEmail VARCHAR(20) NOT NULL,
	senha VARCHAR(12) NOT NULL

);
GO

CREATE TABLE EMPRESA (
	idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(15) NOT NULL

);
GO

CREATE TABLE ARTISTAS (
	idArtistas SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	nomeArtista VARCHAR(15)

);
GO

CREATE TABLE LANCAMENTO (
	idLancamento SMALLINT PRIMARY KEY IDENTITY(1,1),
	idArtistas SMALLINT FOREIGN KEY REFERENCES ARTISTAS(idArtistas),
	dataLancamento VARCHAR(8) NOT NULL

);
GO

CREATE TABLE ALBUM (
	idAlbum SMALLINT PRIMARY KEY IDENTITY(1,1),
	idLancamento SMALLINT FOREIGN KEY REFERENCES LANCAMENTO(idLancamento),
	nomeAlbum VARCHAR(15) NOT NULL

);
GO

CREATE TABLE ESTILO(
	idEstilo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idAlbum SMALLINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
	Genero VARCHAR(15)

);
GO