USE EMPRESA;

SELECT * FROM PESSOA 
SELECT * FROM TELEFONE
SELECT * FROM CNH 
SELECT * FROM EMAIL

SELECT PESSOA.nomePessoa, TELEFONE, EMAIL FROM PESSOA
INNER JOIN TELEFONE
ON PESSOA.idPessoa = TELEFONE.idPessoa
INNER JOIN EMAIL
ON PESSOA.idPessoa = EMAIL.idPessoa
INNER JOIN CNH
ON PESSOA.idPessoa = CNH.idPessoa;
GO