USE VEICULO;
GO

SELECT * FROM EMPRESA
SELECT * FROM VEICULO
SELECT * FROM ALUGUEL
SELECT * FROM CLIENT
SELECT * FROM MODELO
SELECT * FROM MARCA

SELECT ALUGUEL, CLIENT, MODELO.nomeModelo FROM ALUGUEL
INNER JOIN CLIENT
ON ALUGUEL.idCliente = CLIENT.idCLiente
INNER JOIN VEICULO
ON ALUGUEL.idVeiculo = VEICULO.idVeiculo
INNER JOIN MODELO
ON MODELO.idModelo = VEICULO.idModelo;
GO