CREATE DATABASE PETSHOP;
GO

USE PETSHOP;
GO

CREATE TABLE CLINICA(
	idClinica SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeClinica VARCHAR(20) NOT NULL

);
GO

CREATE TABLE VETERINARIO(
	idVeterinario SMALLINT PRIMARY KEY IDENTITY(1,1),
	idClinica SMALLINT FOREIGN KEY REFERENCES CLINICA(idClinica),
	nomeVeterinario VARCHAR(20) NOT NULL

);
GO

CREATE TABLE ATENDIMENTO(
	idAtendimento SMALLINT PRIMARY KEY IDENTITY(1,1),
	idVeterinario SMALLINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
	numeroAtendimento VARCHAR(10) NOT NULL

);
GO

CREATE TABLE PET(
	idPet SMALLINT PRIMARY KEY IDENTITY(1,1),
	idAtendimento SMALLINT FOREIGN KEY REFERENCES ATENDIMENTO(idAtendimento),
	nomePet VARCHAR(15) NOT NULL

);
GO

CREATE TABLE DONO(
	idDono SMALLINT PRIMARY KEY IDENTITY(1,1),
	idPet SMALLINT FOREIGN KEY REFERENCES PET(idPet),
	nomeDono VARCHAR(20) NOT NULL

);
GO


CREATE TABLE RACA(
	idRaca SMALLINT PRIMARY KEY IDENTITY(1,1),
	idPet SMALLINT FOREIGN KEY REFERENCES PET(idPet),
	nomeRaca VARCHAR(15) NOT NULL

);
GO

CREATE TABLE TIPO_PET (
	idTipo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idRaca SMALLINT FOREIGN KEY REFERENCES RACA(idRaca),
	tipoPet Varchar(15) NOT NULL

);
GO